### PR TITLE
registration() & get()

### PR DESCRIPTION
**Pull request by jakearchibald**
***
[Preview](https://s3.amazonaws.com/pr-preview/WICG/background-fetch/registration.html) | [Diff](https://s3.amazonaws.com/pr-preview/WICG/background-fetch/5c0acc8...c3a8949.html)

### CODE REVIEW

**Comment by jakearchibald** [comment]
Will merge this once https://github.com/whatwg/html/pull/3038 lands.

**Comment by jakearchibald** [comment]
@annevk low priority, but I'd like your thoughts on [using this](https://s3.amazonaws.com/pr-preview/WICG/background-fetch/registration.html#get-a-backgroundfetchregistration-instance) to ensure that instances are consistent throughout the life of the client.

**Comment by annevk** [comment]
I don't understand "relevant settings object" there. That needs to be of some other object, which isn't specified?

In `fetch()` I don't understand

> Append bgFetch to registration’s active background fetches.

which seems to append something to a map. (I was trying to figure out how the IDs worked.)

**Comment by jakearchibald** [comment]
> I don't understand "relevant settings object" there.

Ah, you're right. I was looking for something that would have the same lifetime as the global. I'll have another swing at it. I think it might be better to hang this off BackgroundFetchManager.

Are you aware of any other specs that do this explicitly, or is it usually hand-waved?

The aim is for:

```js
const a = await registration.backgroundFetch.get('foo');
const b = await registration.backgroundFetch.get('foo');
assert_equals(a, b);
```

> which seems to append something to a map

Oops. I changed the type and didn't change all uses of it. Fixed.

**Comment by annevk** [comment]
There's probably handwaving, though generally that would indicate bugs. Your setup looked reasonable from that perspective, apart from potentially not being clear what global is being used to create the object. @domenic has been writing lots of tests around that so he can probably advise you better on that front.

**Comment by jakearchibald** [comment]
Merging this now. I'll change the queuing stuff once https://github.com/whatwg/html/pull/3038 lands.

**Pull request merged**
